name: 🏗️ Terraform Simple

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: "S3 bucket name"
        required: true
        type: string

env:
  TF_VERSION: "1.5.7"
  AWS_REGION: "us-east-1"
  ENVIRONMENT: "main"

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}   # <--- deixe esse secret cadastrado (pode estar vazio, se não usar token temporário)
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform validate (no backend)
        working-directory: terraform
        run: |
          terraform init -backend=false
          terraform validate

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform apply
        working-directory: terraform
        run: |
          echo "Applying for bucket: ${{ github.event.inputs.bucket_name }} (env=${{ env.ENVIRONMENT }})"
          terraform apply -auto-approve \
            -var="bucket_name=${{ github.event.inputs.bucket_name }}" \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="aws_region=${{ env.AWS_REGION }}"
